"""Loan sanction letter PDF generation.

Uses fpdf2 (pure Python, no system dependencies) — add to requirements.txt:
    fpdf2==2.8.7

This only builds the PDF bytes. Whether those bytes get emailed, downloaded,
or both is handled by the caller (server.py) and email_sender.py.
"""
from datetime import datetime, timezone
from io import BytesIO
from fpdf import FPDF

BRAND_GREEN = (26, 54, 38)     # matches --sl-primary
BRAND_MUTED = (110, 118, 106)
BRAND_ACCENT = (46, 125, 70)


class SanctionLetterPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(*BRAND_GREEN)
        self.cell(0, 10, "SecureLend", ln=1)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*BRAND_MUTED)
        self.cell(0, 5, "Loan Sanction Letter (Simulated - Academic Project)", ln=1)
        self.ln(4)
        self.set_draw_color(*BRAND_ACCENT)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*BRAND_MUTED)
        self.cell(0, 10, "This is a simulated document generated by an academic fintech demo project. Not a real financial instrument.", align="C")


def _row(pdf, label, value):
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*BRAND_MUTED)
    pdf.cell(60, 8, label)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(20, 20, 20)
    pdf.cell(0, 8, str(value), ln=1)


def generate_sanction_letter(*, loan_doc: dict, user: dict) -> bytes:
    """Returns PDF bytes for an approved loan's sanction letter."""
    pdf = SanctionLetterPDF()
    pdf.add_page()

    now = datetime.now(timezone.utc)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 6, f"Reference: {loan_doc.get('id', '')}", ln=1)
    pdf.cell(0, 6, f"Date: {now.strftime('%d %b %Y')}", ln=1)
    pdf.ln(6)

    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(*BRAND_GREEN)
    pdf.cell(0, 8, f"Dear {user.get('full_name', 'Applicant')},", ln=1)
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(30, 30, 30)
    pdf.multi_cell(0, 6,
        "We are pleased to inform you that your loan application has been approved. "
        "The details of your sanctioned loan are set out below.")
    pdf.ln(6)

    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*BRAND_GREEN)
    pdf.cell(0, 8, "Loan Details", ln=1)
    pdf.ln(1)

    _row(pdf, "Sanctioned Amount", f"Rs. {loan_doc.get('loan_amount', 0):,.0f}")
    _row(pdf, "Purpose", loan_doc.get("purpose", "-"))
    _row(pdf, "Tenure", f"{loan_doc.get('tenure_months', '-')} months")
    _row(pdf, "Interest Rate (p.a.)", f"{loan_doc.get('interest_rate', 0) * 100:.2f}%")
    _row(pdf, "Estimated EMI", f"Rs. {loan_doc.get('estimated_emi', 0):,.0f}/month")
    _row(pdf, "Eligibility Score", f"{loan_doc.get('eligibility_score', '-')}/100")
    _row(pdf, "Risk Tier", loan_doc.get("risk_level", "-"))

    pdf.ln(8)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*BRAND_GREEN)
    pdf.cell(0, 8, "Terms & Conditions (illustrative)", ln=1)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(50, 50, 50)
    terms = (
        "1. This sanction is valid for 30 days from the date of this letter.\n"
        "2. Disbursal is subject to final document verification.\n"
        "3. The interest rate shown is fixed for the tenure of the loan.\n"
        "4. Prepayment is permitted without penalty after 6 EMIs.\n"
        "5. This letter and the underlying decision were generated by an "
        "explainable rule-based scoring engine as part of an academic project; "
        "no real funds are disbursed."
    )
    pdf.multi_cell(0, 5, terms)

    out = pdf.output()
    return bytes(out)